import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import AppNavBar from "./_components/AppNavbar";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ["latin"] });

const menus = [
  { icon: "", label: "About Me", route: "about" },
  { icon: "", label: "Skills", route: "skills" },
  { icon: "", label: "Experiences", route: "experiences" },
  { icon: "", label: "Accomplishments", route: "accomplishments" },
  { icon: "", label: "Contact Me", route: "contact" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${inter.className} antialiased`}>
        <AppNavBar />
        {/* <section
          id="about"
          className="w-full flex flex-wrap justify-evenly items-center"
        > */}
        {children}
        {/* </section> */}
      </body>
    </html>
  );
}
